#!/usr/bin/env bash

export CONTECO_LABEL="schema_registry.sasl - ContEco"
export CONTECO_DESCRIPTION="Confluent Schema Registry image, with SASL authentication."

export CONTECO_TYPE="schema_registry"
export CONTECO_NAME="sasl"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="external.schema_registry:5.4.0"
export CONTECO_BUILD="image-base"
