#!/usr/bin/env bash

export CONTECO_LABEL="schema_registry.sasl - ContEco"
export CONTECO_DESCRIPTION="Confluent Schema Registry image, with SASL authentication."

export CONTECO_TYPE="schema_registry"
export CONTECO_NAME="sasl"
export CONTECO_TAG="6.0.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="confluentinc/cp-schema-registry:6.0.0"
